#!/usr/bin/bash
# Author: Dzmitry.Lahoda@gmail.com
# 
# adds - commits - pushes all changes 
# Example:
#     gitpushall "message"
git add --all;
git commit -m "auto commit";
git push origin master;